name: Lint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Run Ruff
        uses: astral-sh/ruff-action@v3.5.1 
      

  pyright:
    name: Pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies for Pyright
        run: |
          python -m pip install --upgrade pip
          pip install pyright
          pip install -e .
      - name: Run Pyright
        run: |
          pyright src/