name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      run-tests:
        description: 'Run tests before publishing'
        required: false
        default: 'false'
        type: boolean

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install build

      - name: Run tests
        if: ${{ inputs.run-tests == 'true' }}
        run: pytest

      - name: Build package
        run: python -m build

      - name: Show contents of source distribution
        run: |
          echo "📂 Contents of source distribution archive:"
          tar -tf dist/*.tar.gz

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
